"""Generate a self-contained HTML findings report from probe results."""

import html
import json
from datetime import datetime
from typing import Dict, List, Optional

from piscan.aggregate import summarize, ATTACK_CATEGORIES


def _bar(pct: float, color: str) -> str:
    pct = max(0.0, min(100.0, pct))
    return (f'<div class="bar"><div class="fill" style="width:{pct:.1f}%;'
            f'background:{color}"></div></div>')


def generate_html(results: List[Dict], output_path: str,
                  meta: Optional[Dict] = None) -> str:
    meta = meta or {}
    stats = summarize(results)
    ao = stats["attack_overall"]
    detected = [r for r in results
                if r.get("detected") and r.get("category") != "benign"]

    target = html.escape(str(meta.get("target", "unknown")))
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")

    rows = ""
    for c in ATTACK_CATEGORIES:
        cs = stats["attack"][c]
        if cs["attempts"] == 0:
            continue
        rate = cs["rate"] * 100
        color = "#e23744" if rate >= 50 else ("#d98324" if rate > 0 else "#0f9d6e")
        rows += (f"<tr><td>{c}</td><td>{cs['detected']}/{cs['attempts']}</td>"
                 f"<td class='num'>{rate:.1f}%</td><td>{_bar(rate, color)}</td></tr>")

    benign_html = ""
    if stats["benign"]:
        b = stats["benign"]
        col = "#0f9d6e" if b["fp_rate"] == 0 else "#e23744"
        benign_html = (f"<p class='fp'>Benign false-positive rate: "
                       f"<b style='color:{col}'>{b['fp_rate']*100:.1f}%</b> "
                       f"({b['false_positives']}/{b['attempts']} benign replies flagged)</p>")

    findings = ""
    for r in detected:
        verdict = r.get("judge_verdict")
        vtag = (f"<span class='verdict {verdict.lower()}'>{verdict}</span>"
                if verdict else "")
        findings += f"""
        <div class="finding">
          <div class="fhead"><b>{html.escape(str(r.get('payload_id')))}</b>
            <span class="cat">{html.escape(str(r.get('category')))}</span> {vtag}
            <span class="reason">{html.escape(str(r.get('detection_reason','')))}</span></div>
          <div class="resp">{html.escape(str(r.get('response_text',''))[:400])}</div>
        </div>"""
    if not findings:
        findings = "<p>No successful injections detected.</p>"

    doc = f"""<!doctype html><html><head><meta charset="utf-8">
<title>PIScanner Report — {target}</title>
<style>
 body{{font-family:system-ui,Arial,sans-serif;max-width:900px;margin:32px auto;color:#1e293b;padding:0 16px}}
 h1{{margin:0 0 4px}} .sub{{color:#64748b;margin:0 0 20px}}
 .cards{{display:flex;gap:12px;margin:18px 0}}
 .card{{flex:1;background:#f1f5f9;border-radius:10px;padding:14px}}
 .card .big{{font-size:30px;font-weight:700}}
 .card .lbl{{color:#64748b;font-size:12px}}
 table{{width:100%;border-collapse:collapse;margin:10px 0}}
 th,td{{text-align:left;padding:8px;border-bottom:1px solid #e2e8f0}}
 td.num{{font-weight:700}}
 .bar{{background:#e2e8f0;border-radius:6px;height:10px;width:160px;overflow:hidden}}
 .fill{{height:10px}}
 .finding{{background:#fff;border:1px solid #e2e8f0;border-radius:8px;padding:10px;margin:8px 0}}
 .cat{{background:#eef2ff;color:#3730a3;border-radius:10px;padding:1px 8px;font-size:12px}}
 .reason{{color:#64748b;font-size:12px;margin-left:6px}}
 .resp{{font-family:ui-monospace,monospace;font-size:12px;background:#f8fafc;border-radius:6px;padding:8px;margin-top:6px;white-space:pre-wrap;word-break:break-word}}
 .verdict{{border-radius:10px;padding:1px 8px;font-size:12px;color:#fff}}
 .verdict.success{{background:#e23744}} .verdict.refused{{background:#0f9d6e}} .verdict.unclear{{background:#d98324}}
 .warn{{background:#fef3c7;border:1px solid #f59e0b;color:#92400e;padding:10px 14px;border-radius:8px;font-size:13px}}
</style></head><body>
<h1>PIScanner Findings Report</h1>
<p class="sub">Target: <b>{target}</b> &middot; {html.escape(str(meta.get('model','')))} &middot; {ts}</p>
<div class="warn">For authorized security testing only. This report reflects one scan; LLM outputs vary between runs.</div>
<div class="cards">
  <div class="card"><div class="big">{ao['rate']*100:.1f}%</div><div class="lbl">overall attack success ({ao['detected']}/{ao['attempts']})</div></div>
  <div class="card"><div class="big">{len(detected)}</div><div class="lbl">successful injections</div></div>
  <div class="card"><div class="big">{stats['failures']}</div><div class="lbl">failed requests</div></div>
</div>
<h2>By category</h2>
<table><tr><th>Category</th><th>Detected</th><th>Rate</th><th></th></tr>{rows}</table>
{benign_html}
<h2>Findings</h2>
{findings}
<p class="sub" style="margin-top:24px">Generated by PIScanner &middot; https://github.com/lalitbist641/piscan</p>
</body></html>"""

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(doc)
    return output_path
